# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi.yaml:
  no-ambiguous-paths:
    - >-
      #/paths/~1accounts~1{account_identifier}~1images~1v1~1variants~1{identifier}
    - '#/paths/~1accounts~1{account_identifier}~1pcaps~1ownership~1{identifier}'
    - >-
      #/paths/~1accounts~1{account_identifier}~1rules~1lists~1bulk_operations~1{operation_id}
    - '#/paths/~1accounts~1{account_identifier}~1stream~1keys~1{identifier}'
    - >-
      #/paths/~1accounts~1{account_identifier}~1stream~1live_inputs~1{live_input_identifier}
    - '#/paths/~1accounts~1{account_identifier}~1stream~1watermarks~1{identifier}'
    - '#/paths/~1accounts~1{identifier}~1devices~1dex_tests~1{uuid}'
    - '#/paths/~1accounts~1{identifier}~1devices~1networks~1{uuid}'
    - '#/paths/~1accounts~1{identifier}~1devices~1policy~1{uuid}'
    - '#/paths/~1accounts~1{identifier}~1devices~1posture~1{uuid}'
  spec:
    - >-
      #/components/schemas/api-response-single/allOf/1/properties/result/nullable
    - >-
      #/components/schemas/audit_logs_response_collection/oneOf/0/properties/errors/nullable
    - >-
      #/components/schemas/api-response-common-failure-mJQZ9kEB/properties/result/nullable
    - >-
      #/components/schemas/projects/properties/canonical_deployment/oneOf/0/nullable
    - >-
      #/components/schemas/projects/properties/latest_deployment/oneOf/0/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues/get/responses/200/content/application~1json/schema/allOf/1/properties/errors/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues/get/responses/200/content/application~1json/schema/allOf/2/properties/messages/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues/get/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/properties/errors/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues/get/responses/4xx/content/application~1json/schema/allOf/0/allOf/2/properties/messages/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}/delete/responses/200/content/application~1json/schema/allOf/1/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}/delete/responses/200/content/application~1json/schema/allOf/1/properties/result/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}/delete/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}/delete/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/properties/result/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers/get/responses/200/content/application~1json/schema/allOf/1/properties/errors/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers/get/responses/200/content/application~1json/schema/allOf/2/properties/messages/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers/get/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/properties/errors/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers/get/responses/4xx/content/application~1json/schema/allOf/0/allOf/2/properties/messages/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers~1{consumer_name}/delete/responses/200/content/application~1json/schema/allOf/1/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers~1{consumer_name}/delete/responses/200/content/application~1json/schema/allOf/1/properties/result/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers~1{consumer_name}/delete/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/nullable
    - >-
      #/paths/~1accounts~1{account_identifier}~1workers~1queues~1{name}~1consumers~1{consumer_name}/delete/responses/4xx/content/application~1json/schema/allOf/0/allOf/1/properties/result/nullable
    - >-
      #/components/schemas/device-posture-integrations_components-schemas-id_response/allOf/1/properties/result/nullable
    - >-
      #/components/schemas/schemas-filter-response-single/allOf/1/properties/result/oneOf/1/nullable
    - >-
      #/components/schemas/schemas-empty_response-9gKX6yJD/allOf/0/properties/result/nullable
    - >-
      #/components/schemas/schemas-id_response-g5jrgrmA/allOf/1/properties/result/nullable
  path-parameters-defined:
    - >-
      #/paths/~1zones~1{zone_id}~1rulesets~1phases~1{phase}~1entrypoint/get/parameters/0/name
    - >-
      #/paths/~1zones~1{zone_id}~1rulesets~1phases~1{phase}~1entrypoint/get/parameters
    - >-
      #/paths/~1zones~1{zone_id}~1rulesets~1phases~1{phase}~1entrypoint/put/parameters/0/name
    - >-
      #/paths/~1zones~1{zone_id}~1rulesets~1phases~1{phase}~1entrypoint/put/parameters
  operation-parameters-unique:
    - '#/paths/~1zones~1{zone_identifier}~1logs~1received/get/parameters/4'
  no-enum-type-mismatch:
    - '#/components/schemas/verification_info/enum/0'
    - '#/components/schemas/verification_info/enum/1'
    - '#/components/schemas/verification_info/enum/2'
    - '#/components/schemas/verification_info/enum/3'
    - '#/components/schemas/verification_info/enum/4'
    - '#/components/schemas/verification_info/enum/5'
    - '#/components/schemas/verification_info/enum/6'
    - '#/components/schemas/verification_info/enum/7'
  no-unused-components:
    - '#/components/schemas/access-requests'
    - '#/components/schemas/access-requests_components-schemas-identifier'
    - '#/components/schemas/address-maps-membership'
    - '#/components/schemas/alert-types'
    - '#/components/schemas/apps_components-schemas-identifier'
    - '#/components/schemas/bookmarks'
    - '#/components/schemas/bookmarks_components-schemas-identifier'
    - '#/components/schemas/certificateObjectPost'
    - '#/components/schemas/components-schemas-certificateObject'
    - '#/components/schemas/custom-certificate'
    - '#/components/schemas/default_device_settings_policy'
    - '#/components/schemas/deployment_stage_name'
    - '#/components/schemas/device_settings_policy'
    - '#/components/schemas/devices'
    - '#/components/schemas/eligibility'
    - '#/components/schemas/enabled_write'
    - '#/components/schemas/feature_app_props'
    - '#/components/schemas/hostname_certid_input'
    - '#/components/schemas/hostname_post'
    - '#/components/schemas/identity-providers_components-schemas-identifier'
    - '#/components/schemas/ips-Bladqxra'
    - '#/components/schemas/keys_components-schemas-identifier'
    - '#/components/schemas/name_write'
    - '#/components/schemas/new_custom_entry'
    - '#/components/schemas/organizations_components-schemas-identifier'
    - '#/components/schemas/policies_components-schemas-identifier'
    - '#/components/schemas/request-tracer'
    - '#/components/schemas/revoke_devices_request'
    - '#/components/schemas/schemas-app_id'
    - '#/components/schemas/schemas-certificateObject'
    - '#/components/schemas/schemas-phase'
    - '#/components/schemas/seats_components-schemas-identifier'
    - '#/components/schemas/self_hosted_props'
    - '#/components/schemas/sslpost'
    - '#/components/schemas/transform-rules_components-schemas-ruleset'
    - '#/components/schemas/type-xx5tZh1p'
    - '#/components/schemas/unrevoke_devices_request'
    - '#/components/schemas/update_custom_profile'
    - '#/components/schemas/users'
    - '#/components/schemas/users_components-schemas-identifier'
    - '#/components/schemas/waf_action'
  security-defined:
    - '#/paths/~1zones~1{zone_id}~1activation_check/put'
