name: Get all URLs and begin crawling

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        uses: tj-actions/puppeteer@v4
        id: puppeteer
        with:
          files: |
            .github/workflows/crawl.js
        env:
          ALGOLIA_CRAWLER_API_KEY: ${{secrets.ALGOLIA_CRAWLER_API_KEY}}
          ALGOLIA_CRAWLER_ID: ${{secrets.ALGOLIA_CRAWLER_ID}}
          ALGOLIA_CRAWLER_URL: ${{secrets.ALGOLIA_CRAWLER_URL}}
          ALGOLIA_CRAWLER_USER_ID: ${{secrets.ALGOLIA_CRAWLER_USER_ID}}
